### ISSUE TITLE
Changes in atto_equation

### ISSUE THREAD

**Issue by Kathrin84** [geoffrowland/moodle-editor_atto-chemistry#5]
Hi,

we're using your atto plugin and are updating to Moodle 2.9. I've tested your plugin and it works fine in the new Moodle version.
Nevertheless, I just wanted to tell you that there have been some cosmetic code changes in the javascript files of atto_equation.
You could transfer those changes into the code of your plugin to stay consistent with the basis.

Kind regards
Kathrin

**Comment by geoffrowland** [comment]
Hi Kathrin,

Thanks for the 'nudge'. I was aware that there have been some changes with the JavaScript  in atto_equation and Moodle 2.9 but had not got round to merging those with the chemistry editor. I hope to take a look at this over the next few days.

Also, have been tinkering with some reorganisation of the tabs and addition of more default symbols to atto_equation editor. Will try to get these into Moodle core too.

See e.g.
https://tracker.moodle.org/browse/MDL-45067
https://tracker.moodle.org/browse/MDL-50936
https://github.com/gjb2048/moodle-theme_essential/issues/522

**Comment by geoffrowland** [comment]
Hi Kathrin
Code now merged with latest (Moodle 2.9) atto_equation.
Thanks again
Geoff
